name: Notificador de Mercados

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:  # te permite ejecutarlo manualmente para probar

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot_mercados.py
